[package]
name = "rust-play"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
serde_json = "1.0.69"
serde = "1.0.130"
serde_derive = "1.0.130"
urlencoding = "2.1.0"